### ISSUE TITLE
off-canvas example?

### ISSUE THREAD

**Issue by titaniumbones** [gpspake/grunterie#12]
Hi @gpspake, 

I'm just checking out grunterie, it looks great so far.  Am considering using it as the basis for a series of student projects this fall (we used to use required+ but this is much cleaner, actually).  

In a couple of places o nthe web you've talked about offcanvas menus for grunterie.  Do you have any code snippets to share?  Thanks,

Matt

**Comment by jamzth** [comment]
Not that this is a perfect example or anything. But a while back, I did eastmemorial.org with an off-canvas for small screens. Maybe it will help. It was based on reverie, so nothing significant should change for grunterie. Hope that gets you in the right direction at least.

**Comment by gpspake** [comment]
@jamzth Thanks for the example; it looks nice. And @titaniumbones, sorry for letting this go.

I've used foundation's off canvas nav with reverie before but there are some things I don't like about it's behavior so I've been using my own version of another off-canvas library.

I don't know if off canvas in the scope of this theme because I want to keep it as simple and as close to Reverie as I can, but I did intend to get an example up at some point so I don't want to close this issue out yet. I've just been busy.

**Comment by jamzth** [comment]
@gpspake do you want my example and tweak to for the example you want out there? That'll close the issue, help @titaniumbones, and possibly easier on you.

**Comment by gpspake** [comment]
I'm going to close this issue since I've left it open for a while now. For the sake of keeping the theme as simple, un-opinionated and similar to Reverie as possible, I think including some sort of off canvas option is outside of the scope of the project. @jamzth If you want to post your approach somewhere, it might be helpful to others.
