### ISSUE TITLE
Vanilla CSS with grunterie?

### ISSUE THREAD

**Issue by squidzink** [gpspake/grunterie#22]
I ended up here because I've been trying to get data-equalizer to work with Reverie, saw you had additional updates in your fork. 

However, I haven't dived into sass yet. I'm curious if grunterie works as a vanilla css version?

I actually have it loaded but I notice the theme's CSS file is thousands of lines long rather than the 900+ in the original version.

I want to get into sass, but when the schedule is already intense, I don't think I can afford the time to figure out the compiling process and additional software and the perks of sass with deadlines pushing already. But I'd sure like to get equalizer to work dang it.

**Comment by gpspake** [comment]
hey @squidzink Grunterie is best with sass and I'd definitely encourage you to take the time to look in to it... I assure you it's time well spent. Once you use sass, you might never want to just use plain css again.) You could use your own css but the time you would spend wrangling it against foundations stylesheets would probably be better spent walking through the process to set up and use sass. 

The [foundation docs are great for getting a sass project started](http://foundation.zurb.com/docs/sass.html); I would recommend walking through those instructions to get an idea of why the theme is organized the way it is. Note: about halfway down the page under 'Compiling Sass into CSS & Creating a Project, follow the directions under 'Creating A Libsass Project'

Once you have sass set up, you can change pretty much everything about the theme really easily in the [settings file](https://github.com/gpspake/grunterie/blob/master/scss/_settings.scss) and add everything else (you can even just write plain ol' css) to [these files](https://github.com/gpspake/grunterie/tree/master/scss/partials) - Way quicker and more fun than writing a bunch of css.

**Comment by squidzink** [comment]
Thanks @gpspake. I totally understand. I really do plan to get on the sass train. I have a couple of issues to consider right now. The equalizer thing that got me here is in a project that is trying to get details wrapped up and it time critical. My second concern: young/green folk I have working on some projects and how I roll them into the scenario gracefully...especially when I'm not sure I'm rolling in gracefully. 

Though I've been reading over sass info for nearly a year, I'm still not clear on the compiling stuff. I need to do a test drive when I have some breathing room or on a project I know I can withstand trial by fire. I had previously downloaded Foundation's blank sass-based theme as well, but haven't cracked the seal there either.

All that said, I'm super stoked to see that you've jumped in to keep Reverie/Grunterie moving along. It's been a great blank canvas even using vanilla CSS. And, thanks a mil for the quick reply.

**Comment by gpspake** [comment]
@squidzink not sure it'll help but once you get your head around it it's pretty simple: grunt is what we use to compile our sass in to css stylesheets. grunt watches the scss files for changes and updates recompiles them in to css anytime you save one of the scss files. All the information about the tasks that compile sass are in the [gruntfile](https://github.com/gpspake/grunterie/blob/master/Gruntfile.js); with foundation/reverie, though, all of the tasks are set up for you so all you have to do is run 'grunt' - Just one command.

Now, to run grunt you have to have it installed and, since grunt runs on node, you have to install node as well. Node comes with npm (node package manager) which you'll use to install grunt and bower. So what's bower? Bower is another package manager that pulls in stuff like jQuery and other frontend dependencies.

So to use foundation/reverie:
(Not: If you're in windows I recommend using the git bash shell or another nix like shell as opposed to cmd)
- install git
- install node/npm
- install grunt/bower
- from the command line, go to [the root directory of foundation](https://github.com/gpspake/grunterie) (in this case the grunterie theme directory) 
- run 'npm update'
- run 'bower update'
- run 'grunt' from the command line. Grunt is now watching your scss files until you stop the process (ctrl+c)
- Edit the settings.scss file or the scss files in the partials directory
- Now, any time you make changes to one of the scss files and save it, grunt will automatically update the css files in the css directory.

That's probably a little oversimplified but that's the gist of it.
If I seem like I keep going back to scss, it's because I feel like it would be more productive than editing css in to your project when it's built from the ground up to use sass. If you wanted to, you could add css to [style.css](https://github.com/gpspake/grunterie/blob/master/css/style.css) but it's probably going to cause you a lot more headaches than it would to use sass. I know it's tricky and you might run in to some roadblocks along the way but I might be able to help if you have any issues.
One of my favorite comics:
![Technical Debt](https://pbs.twimg.com/media/CB_3iJUUgAAA7_4.jpg)

**Comment by squidzink** [comment]
Hehe. So true.

Ok. You're getting me motivated. I'll start working on seeing if I can get setup to test drive. I surely don't want to continue on my square wheels!

Truly appreciate the info. I'll let you how it goes as I chip off some time to roll.

**Comment by squidzink** [comment]
@gpspake It seems like I was able to set up the project properly and I can turn on and off Grunt in Terminal. However I don't know how to tell if it's working being the noob with the whole compiling scenario. I cannot affect any visible change by uncommenting lines in the _settings.scss file or any of the partial files. 

I seem to be missing something simple that I just don't get yet.

A couple of questions:
- how do I determine if the project was actually up correctly?
- how will I set up another project for a new site later? Does grunt watch all of them at once?

I think I need some resources to help me understand how this set up works. But what I keep finding tends to assume I know more about the tools than I do.

**Comment by squidzink** [comment]
Ok, I believe I'm having an installation problem. I've trashed the grunterie theme folder 5 times and have tried to setup the project repeatedly using the steps for libsass here http://foundation.zurb.com/docs/sass.html. But I'm still missing something. 

When I setup the "project" by running foundation new project_name --libsass, should I be in the grunterie directory? 

I'm also not really clear on how to edit the _settings.scss file. Is all of the stuff with "//" before it inactive and simply loading Foundation defaults? I've changed color references on text and background colors but nothing changes.

Should the /css/styles.css file show that it has been recently saved if it is compiled? 

Is there some way to determine if the dang project was setup correctly...a file that should have the project name in it or something? 

It would be great to get past this set up hurdle. I've hit a wall, likely due to inexperience.

**Comment by jamzth** [comment]
You should be able to install bower and grunt from the folder and then run grunt after that. No need to follow the set up using the foundation gem with libsass like that. Others may need to correct me on that, but it works for me. Also, I hope I explained that well enough. If not, let me know.

**Comment by squidzink** [comment]
@jamzth if I assume I have Git and node.js and grunt CLI globally installed properly (may not be a good assumption), what are the steps to set up the "project" from there? Are you saying I just need to go to the grunterie directory in Terminal and then run 'bower update' and 'npm update' then run 'grunt'?

Whatever it is I'm missing seems to be related to whatever ties the actual project to the stuff that has been installed globally. When you say "install bower and grunt from the folder," I don't really know what that means for sure...even the actual command that you're referring to. I just don't know my way around this process yet. Seemed like a simple set up, but now my brain is having calculus fail flashbacks.

**Comment by squidzink** [comment]
@gpspake , @jamzth apologies for leaning on y'all to try and troubleshoot. 

Facts: 
- node, npm, grunt, bower are installed globablly in usr/local/bin. I can see them if I "Go to Folder" 
- I do not know what to do next
- If I try to run 'npm update' from the "grunterie" directory it will fail. 
- If it try to run 'grunt' from the "grunterie" directory it will fail saying it is not installed locally.
- If I try the libsass set up listed here http://foundation.zurb.com/docs/sass.html instead, I can create a nice "grunterie" directory that seems to have all of the proper dependencies etc in it but it will be missing all of the grunterie stuff. I could not determine what I might copy over from "grunterie-master" to make it whole, The fact that I was trying to do that seems to indicated proper steps aren't being done.

I apparently need a step by step specifically for getting grunterie sassed. I've run through around 15 rounds trying different things to no avail. The problem is really that I'm pretty much clueless as to how the components work together, what the specific files are etc. 

From what I understand, if things are set up correctly, I can make edits to the _settings.scss file and a new styles.css file will automatically be compiled and saved. But alas, I clearly cannot get things set up properly.

**Comment by squidzink** [comment]
A recurring error:

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by squidzink** [comment]
Finally got it. 

Set grunterie theme folder
ran bower update
ran npm update or install -- failed due to no node-sass@1.2.3
--- Searching errors I found a post related to node 0.12 having a problem with older node-sass. 
--- Saw note to specifically load node-sass@2.0.1 to overcome
ran npm install node-sass@2.0.1
ran grunt -- failed missing grunt-sass
ran npm install grunt-sass
ran grunt
...waiting
Test edited _settings.scss

Noted styles.css saved anew.
Noted Terminal grunt run without errors

Reloaded front end of grunterie based WP site. Success. 

Gracias for the nudge to dive in @gpspake, the guidance as well from @jamzth and the tolerance of this thread. If that was the only problem with the setup, man...it burned a load of time. Harsh. 

Onward!

**Comment by jamzth** [comment]
@squidzink
I wish I had time to help more today! Been running around everywhere. I'm glad that you were able to get it up and going finally. I had trouble at first too, but solely due to my nubby knowledge as well. I think I spent around 3-5hrs getting it up the first time and about 30sec per project ever since. I'm sure that grunterie won't disappoint. @gpspake has pushed reverie into a very useful and up to date framework. I use it for all of my projects!

**Comment by gpspake** [comment]
@squidzink, Nice! You got it!? Great work. 
I'll go ahead and close this thread but if you run in to any issues, just open a new one or post here and I'll try to get to it as soon as I can.
Thanks a ton for helping out here, @jamzth.

**Comment by squidzink** [comment]
Thanks!!

--
Cole Schweikhardt
